services:
  FrontEnd:
    build: "./FrontEnd"
    ports:
      - "3000:3000"
    network:
      - "mern"
  Backend:
    build: "./BackEnd"
    ports:
      - "5000:5000"
    network:
      - "mern"
    depends_on:
      - db
    db:
    image: db:latest
    ports:
      - "27017:27017"
    volumes:
      - db-data: "./data/db"
  Network:
    mern:
      driver: bridge
    volumes:
      db-data: 
        driver : local
    
